services:
  postgres-nio-notes:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=nishat
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=nio-notes
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nishat"]
      interval: 10s
      retries: 3

volumes:
  postgres-data:
