services:
  app:
    image: oven/bun:latest
    container_name: bun-app
    working_dir: /app
    environment:
      - DATABASE_URL=postgres://nishat:1234@postgres-nio-notes:5432/nio-notes
      - NEXTAUTH_URL=http://localhost:3000
      - PORT=3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres-nio-notes
    command: bun --bun run dev --port 3000

  postgres-nio-notes:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=nishat
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=nio-notes
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nishat"]
      interval: 10s
      retries: 3

volumes:
  postgres-data:
